language: go
go:
    - 1.7.x
script:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - make
  - make clean
notifications:
  email:
    on_success: change
    on_failure: change
