export BOARD_TAG=Mega2560
export ARDUINO_LIBS="SoftwareSerial"
export ARDUINO_DIR=/usr/share/arduino
export ARDMK_DIR=/usr/share/arduino
export AVR_TOOLS_DIR=/usr
include /usr/share/arduino/Arduino.mk
